### ISSUE TITLE
cannot find --skip and --force flag during download.

### ISSUE THREAD

**Issue by jd730** [wkentaro/gshell#15]
Hi, I got an error that 
`File '<>' already exists, use --force to overwrite or --skip to skip` while resuming download. 

When I tried to use skip flag as follows :
`gshell download --with-id <> --recursive --force`

I got an error that `Error: no such option: --skip`, and there is no description about skip and force flag on `ghsell download -h`

Thank you.

**Comment by wkentaro** [comment]
This is because gshell wraps gdrive: https://github.com/gdrive-org/gdrive, so the error comes from gdrive instead of gshell command.

**Comment by jd730** [comment]
Thank you!

**Comment by rabinadk1** [comment]
Is there any way to specify it from gshell?
