### ISSUE TITLE
Sign in disabled

### ISSUE THREAD

**Issue by keflavich** [wkentaro/gshell#18]
I get the following message when trying to log in:
![image](https://user-images.githubusercontent.com/143715/71017215-41552780-20c4-11ea-8aa0-48511f0f4b80.png)

Is there an additional app verification step that needs to be done with google?

**Comment by stingalleman** [comment]
still no fix?

**Comment by Santosh-Gupta** [comment]
I just got this message too

**Comment by kingralph80** [comment]
Yes me too. Looks like the developers left the app

**Comment by C0ldstudy** [comment]
Same error.

**Comment by wkentaro** [comment]
with this notice from gdrive: https://github.com/prasmussen/gdrive#news
